include: package:lint/analysis_options.yaml

# TODO: implicit casts should be fine, but we'll play the game later
analyzer:
  strong-mode:
    implicit-casts: true
  exclude:
    - lib/**/*.g.dart
    - test/_data/**

linter:
  rules:
    # TODO: convert to true
    prefer_const_constructors: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    prefer_typing_uninitialized_variables: false
    empty_catches: false
    avoid_dynamic_calls: false
    prefer_constructors_over_static_methods: false
    curly_braces_in_flow_control_structures: true
    # sort_constructors_first: true
    # always_put_required_named_parameters_first: true
    # always_specify_types: true

    # Disabled
    file_names: false
    type_annotate_public_apis: false
    avoid_classes_with_only_static_members: false
    always_declare_return_types: false # can be explicit in declaration
    constant_identifier_names: false
    avoid_escaping_inner_quotes: false
    prefer_for_elements_to_map_fromIterable: false # that syntax is challenging, will change if becomes standard
    prefer_conditional_assignment: false
    sized_box_for_whitespace: false
    always_use_package_imports: false
    require_trailing_commas: false

    use_build_context_synchronously: false # powers most of the navigation...

    # Enabled
    prefer_single_quotes: true
    prefer_const_declarations: true
